# Pérez Angeles Adrián

1. Elabora una función que reciba una lista y regrese el promedio de los elementos.

In [3]:
import numpy as np
def l_prom(a):
    sum=0
    for i in range(len(a)):
        sum+=a[i]
    p=sum/ len(a)    
    return p
x=np.array([1,5,3,6])
print(l_prom(x))

3.75


2. Elabora un programa en el cual introduzcas los elementos de un vector por
medio del teclado y te imprima en pantalla el elemento máximo.

In [19]:
l=[]
while True:
    x=float(input("Introduce valores de un vector o presiona 0 para salir "))
    if(x == 0):
        l.sort()
        break
    else:
        l.append(x)
print("El elemento maximo es: ", l[-1])

Introduce valores de un vector o presiona 0 para salir 1
Introduce valores de un vector o presiona 0 para salir 234
Introduce valores de un vector o presiona 0 para salir 12.654
Introduce valores de un vector o presiona 0 para salir 67
Introduce valores de un vector o presiona 0 para salir 3
Introduce valores de un vector o presiona 0 para salir 2
Introduce valores de un vector o presiona 0 para salir 0
El elemento maximo es:  234.0


3. Escribe una función que reciba tres vectores y regrese la combinación de producto
punto y producto vectorial dada por la identidad vectorial:
    $$\vec{A}.\vec{B} x \vec{C}=\vec{B}.\vec{C}x\vec{A}=\vec{C}.\vec{A}x \vec{B}$$

In [11]:
import numpy as np
def trip_prod(a,b,c):
    sum=0
    n,m, o=len(a), len(b), len(c)
    if (n!=m!=o or n!=3):
        return 'Vectores con dimensiones distintas '
    else:
        d0=a[0]*(b[1]*c[2]-b[2]*c[1])
        d1=a[1]*(b[2]*c[0]-b[0]*c[2])
        d2=a[2]*(b[0]*c[1]-b[1]*c[0])
        d=[d0 ,d1 ,d2]
        print("El producto vectorial es: ", d[::])
        for i in range(n):
            sum += d[i]
        return sum
A=np.array([3,2,1])
B=np.array([2,3,2])
C=np.array([1,1,3])
A1=B
B1=C
C1=A
A2=C
B2=A
C2=B
print("El triple producto escalar A.BxC es: ", trip_prod(A,B,C))
print("El triple producto escalar B.CxA es: ", trip_prod(A1,B1,C1))
print("El triple producto escalar C.AxB es: ", trip_prod(A2,B2,C2))

El producto vectorial es:  [21, -8, -1]
El triple producto escalar A.BxC es:  12
El producto vectorial es:  [-10, 24, -2]
El triple producto escalar B.CxA es:  12
El producto vectorial es:  [1, -4, 15]
El triple producto escalar C.AxB es:  12


4. Escribe una función que reciba tres vectores y regrese el producto vectorial,
usando la identidad vectorial:
    $$\vec{A}x(\vec{B}x\vec{C})=(\vec{C}x\vec{B})x\vec{A}=\vec{B}(\vec{A}.\vec{C})-\vec{C}(\vec{A}.\vec{B})$$

In [16]:
def cruz (a,b):
    n,m= len(a),len(b)
    if n!=m or n !=3:
        return 'Con estos vectores no funciona '
    else :
        c0=a [1]* b[2] -a [2]* b [1]
        c1=a [2]* b[0] -a [0]* b [2]
        c2=a [0]* b[1] -a [1]* b [0]
        c=[c0 ,c1 ,c2]
        return c
def prod_vec(a,b,c):
    n, m, o=len(a), len(b), len(c)
    if(n!= m!= o or n!= 3):
        return 'Vectores con dimensiones distintas '
    else:
        suma1 =0
        suma2 =0
        suma3 =0
        for i in range (n):
            suma1+= a[i]*c[i]
            suma2 +=a[i]*b[i]
        return suma1*b - suma2*c
A=np.array([2,2,5])
B=np.array([1,2,3])
C=np.array([1,1,1])
BxC=cruz(B,C)
CxB=cruz(C,B)
print("El producto vectorial AxBxC es: ", cruz(A,BxC))
print("El producto vectorial AxBxC es: ", cruz(CxB,A))
print("El producto vectorial B(A.C)-C(A.B) es: ", prod_vec(A, B, C))

El producto vectorial AxBxC es:  [-12, -3, 6]
El producto vectorial AxBxC es:  [-12, -3, 6]
El producto vectorial B(A.C)-C(A.B) es:  [-12  -3   6]


5. Construya un cuadrado mágico con los nueve primeros números pares de modo
que las filas, columnas y diagonales sumen 30.

In [136]:
from numpy import *
N= float ( input ('Da la propiedad \t'))
A= zeros ([3 ,3])
A[0 ,0]= 8
A[2, 0]= 4
a=N /3.0
b=A[0 ,0] -a
c=a-A[2 ,0]
# Rellenando el cuadrado mágico
A[0 ,1]=a -(b+c)
A[0 ,2]=a+c
A[1 ,0]=a -(b-c)
A[1 ,1]=a
A[1 ,2]=a+(b-c)
A[2 ,1]=a+(b+c)
A[2 ,2]=a-b
print (A)

Da la propiedad 	30
[[ 8.  6. 16.]
 [18. 10.  2.]
 [ 4. 14. 12.]]


6. Construye un cuadrado mágico de 4x4 (suma=34). Los elementos de cada una
de las nueve matrices 2x2 que componen el cuadrado también deben sumar 34.

7. Construye tu propio algoritmo de solución de cuadrados mágicos de 5x5.

8. Haz una función que permita calcular la desviación estándar $\sigma$ de una lista de
números $(N \leq 15)$. Sabiendo que:
    $$\sigma = \sqrt{\frac{\sum_{i=1}^{n}(x_{i}-m)^{2}}{n-1}}$$

In [7]:
import numpy as np
from math import *
def l_prom(a):
    sum=0
    for i in range(len(a)):
        sum+=a[i]
    p=sum/ len(a)    
    return p
def desvi_estand(X):
    N=len(X)
    s=0
    for i in range(N):
        s+=(X[i]-l_prom(X))**2
    sig=sqrt(s/(N-1))
    return sig
A=[1,2,3,4,53, 23,12]
print(desvi_estand(A), l_prom(A))

18.88562063228706 14.0


9. Escribe una función que reciba una matriz y regrese la matriz transpuesta

In [4]:
from numpy import * 
def transpuesta(M):
    ren_M=len(M)
    col_M=len(M[0, :])
    M_t=zeros([ col_M , ren_M ], float )
    for i in range(ren_M):
        for j in range(col_M):
            M_t[j, i]=M[i, j]
    return M_t
A= array([[1 ,2 ,3], [4 ,5 ,6]] , int)
print("La matriz es: \n",A)
print("Y su matriz transpuesta es: \n ",transpuesta(A))

La matriz es: 
 [[1 2 3]
 [4 5 6]]
Y su matriz transpuesta es: 
  [[1. 4.]
 [2. 5.]
 [3. 6.]]


10. Escribe una función que reciba una matriz compleja y regrese la matriz compleja
conjugada.

In [3]:
from numpy import *
def M_Compleja(M):
    ren_MC=len(M)
    col_MC=len(M[0, :])
    MC=zeros([ren_MC, col_MC], complex)
    for i in range(ren_MC):            
        for k in range(col_MC):
            MC[i,k]=M[i, k].conjugate()
    return MC
A= array([[1+3j ,2-1j ,3+2j], [4-5j ,5+1j ,6-7j], [1-1j, 2-2j, 3-3j]] , complex)
print((M_Compleja(A)))


[[1.-3.j 2.+1.j 3.-2.j]
 [4.+5.j 5.-1.j 6.+7.j]
 [1.+1.j 2.+2.j 3.+3.j]]


11. Escribe una función que reciba dos matrices y regrese la suma matricial.

In [4]:
from numpy import *
def sum_mat(A, B):
    ren_A=len(A)
    col_A=len(A[0, :])
    ren_B=len(B)
    col_B=len(B[0, :])
    if(ren_A!=ren_B or col_A!=ren_B):
        return 'Operación no valida'
    else:
        C=zeros([ren_A, col_A], float)
        for i in range(ren_A):
            for j in range(col_B):
                C[i,j]=A[i,j]+B[i,j]
        return C
A= array([[1 ,2 ,3], [4 ,5 ,6],  [1, 1, 1]] , int)
B= array([[1 ,2 ,3], [4 ,5 ,6],  [1, 1, 1]] , int)
print(sum_mat(A,B))

[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [ 2.  2.  2.]]


12. Escribe una función que reciba una matriz y un escalar y regrese la multiplicación del escalar por la matriz.

In [5]:
from numpy import *
K=float(input("dame un escalar "))
def MultEsc(M):
    ren_A=len(A)
    col_A=len(A[0, :])
    C= zeros([ren_A, col_A], float)
    for i in range(ren_A):
        for j in range(col_A):
            C[i,j]=K*A[i,j]
    return C
A= array([[1 ,2 ,3], [4 ,5 ,6],  [1, 1, 1]] , int)
print(MultEsc(A))

dame un escalar 5
[[ 5. 10. 15.]
 [20. 25. 30.]
 [ 5.  5.  5.]]


13. Escribe una función que reciba una matriz y regrese la matriz inversa usando
el algoritmo de Gauss-Jordan.

In [9]:
from numpy import *
from numpy.linalg import *
def gauss_jordan(X):
    X1=X.copy()
    n=len(X)
    c=eye(n)
    c1=c.copy()
    for i in range(n-1):
        if X1[i,i]==0:
            X1[i]=X[i+1]
            X1[i+1]=X[i]
            c1[i]=c[i+1]
            c1[i+1]=c[i]
        if X1[-1,-1]==0:
            X1[-1]=X[0]
            X1[0]=X[-1]
            c1[-1]=c[0]
            c1[0]=c[-1]
    for i in range(n):
        for j in range(n):
            if X1[i,i]!=0 and i!=j:
                mult=(X1[j,i]/X1[i,i])
                X1[j]=X1[j]-mult*X1[i]
                c1[j]=c1[j]-mult*c1[i]
    for i in range(n):
        div=X1[i,i]
        X1[i]=X1[i]/div
        c1[i]=c1[i]/div
    return c1
A1 = array([[ 4,-12,-2,1 ],
           [ -2,0,6,0 ],
           [ 1,9,0,-1 ],
           [ -1,-1,0,0]], float)
M=gauss_jordan(A1)
print('La Matriz inversa es:\n',M)
print('Comprobación de que si es la inversa:')
print(array(dot(A1,M),int))

La Matriz inversa es:
 [[ 0.13636364  0.04545455  0.13636364 -0.40909091]
 [-0.13636364 -0.04545455 -0.13636364 -0.59090909]
 [ 0.04545455  0.18181818  0.04545455 -0.13636364]
 [-1.09090909 -0.36363636 -2.09090909 -5.72727273]]
Comprobación de que si es la inversa:
[[1 0 0 0]
 [0 0 0 0]
 [0 0 1 0]
 [0 0 0 1]]
